apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    name: config
    app: b2b-stage
spec:
  type: ClusterIP
  selector:
    name: config
    app: b2b-stage
  ports:
    - port: 8088
      targetPort: 8088