apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    name: discovery
    app: b2b-stage
spec:
  type: ClusterIP
  selector:
    name: discovery
    app: b2b-stage
  ports:
    - port: 8061
      targetPort: 8061