apiVersion: v1
kind: Service
metadata:
  name: fe-admin
  labels:
    name: fe-admin
    app: b2b-stage
spec:
  type: LoadBalancer
  selector:
    name: fe-admin
    app: b2b-stage
  ports:
    - port: 80
      targetPort: 80