apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: b2b-stage
spec:
  type: LoadBalancer
  selector:
    name: mongodb
    app: b2b-stage
  ports:
    - port: 27017
      targetPort: 27017