apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: b2b-stage
spec:
  type: LoadBalancer
  selector:
    name: mysql
    app: b2b-stage
  ports:
    - port: 3306
      targetPort: 3306