apiVersion: v1
kind: Service
metadata:
  name: super-admin
  labels:
    name: super-admin
    app: b2b-stage
spec:
  type: ClusterIP
  selector:
    name: super-admin
    app: b2b-stage
  ports:
    - port: 8050
      targetPort: 8050