apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: b2b-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
      app: b2b-stage
  template:
    metadata:
      name: mongodb
      labels:
        name: mongodb
        app: b2b-stage
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.1
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: ConcordApp
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Concord&%$#432