apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    app: b2b-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
      app: b2b-stage
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
        app: b2b-stage
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.36
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Concord&%$#234